"""Memory artifact generator for the memory subsystem.

Turns structured scan/model data into human- and agent-readable markdown.
This module produces *content strings only* — it never writes to disk.
All disk I/O is handled by ``writer.py``.

Design constraints
------------------
- Deterministic: same inputs always produce the same string.
- Concise: optimised for agent context windows, not human prose.
- Graceful degradation: produces useful output even when signals are weak.
- No LLM calls: all generation is template/heuristic-driven.

Public API (this ticket)
------------------------
generate_repo_summary(scan)       -> str  (content for repo.md)
generate_architecture_doc(scan)   -> str  (content for architecture.md)
"""

from __future__ import annotations

from pathlib import Path

from .scanner import RepoScan
from .writer import render_markdown_section

# ---------------------------------------------------------------------------
# repo.md
# ---------------------------------------------------------------------------

_REPO_PREAMBLE = (
    "> This file is auto-generated by repo-memory. "
    "Edit `.agent-memory/overrides/` to add human corrections."
)


def generate_repo_summary(scan: RepoScan) -> str:
    """Generate content for ``.agent-memory/repo.md``.

    Args:
        scan: A populated :class:`~scanner.RepoScan`.

    Returns:
        Markdown string suitable for writing directly to ``repo.md``.
    """
    sections: list[str] = []

    # H1 title
    repo_name = scan.repo_root.name or "this-repo"
    sections.append(f"# Repo: {repo_name}\n\n{_REPO_PREAMBLE}")

    # Purpose / stack
    sections.append(render_markdown_section(
        "Stack",
        _render_stack(scan),
    ))

    # Top-level structure
    sections.append(render_markdown_section(
        "Top-level structure",
        _render_top_level(scan),
    ))

    # Where things live
    sections.append(render_markdown_section(
        "Key locations",
        _render_key_locations(scan),
    ))

    # Starting points
    sections.append(render_markdown_section(
        "Suggested starting points",
        _render_starting_points(scan),
    ))

    # Ambiguity notes
    if scan.notes:
        sections.append(render_markdown_section(
            "Detection notes",
            _render_notes(scan.notes),
        ))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# architecture.md
# ---------------------------------------------------------------------------

_ARCH_PREAMBLE = (
    "> Auto-generated architectural overview. "
    "Confidence: {confidence:.0%}. "
    "Add corrections in `.agent-memory/overrides/`."
)


def generate_architecture_doc(scan: RepoScan) -> str:
    """Generate content for ``.agent-memory/architecture.md``.

    Args:
        scan: A populated :class:`~scanner.RepoScan`.

    Returns:
        Markdown string suitable for writing directly to ``architecture.md``.
    """
    sections: list[str] = []

    repo_name = scan.repo_root.name or "this-repo"
    preamble = _ARCH_PREAMBLE.format(confidence=scan.confidence)
    sections.append(f"# Architecture: {repo_name}\n\n{preamble}")

    # Major boundaries
    sections.append(render_markdown_section(
        "Major boundaries",
        _render_boundaries(scan),
    ))

    # Architectural layout
    sections.append(render_markdown_section(
        "Inferred layout",
        _render_layout(scan),
    ))

    # Coupling / ambiguity
    coupling = _render_coupling_notes(scan)
    if coupling:
        sections.append(render_markdown_section(
            "Coupling and ambiguity notes",
            coupling,
        ))

    # Inspect first
    sections.append(render_markdown_section(
        "Inspect first",
        _render_inspect_first(scan),
    ))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# Section renderers — repo.md
# ---------------------------------------------------------------------------


def _render_stack(scan: RepoScan) -> str:
    lines: list[str] = []

    if scan.languages:
        lines.append(f"- **Languages**: {', '.join(scan.languages)}")
    else:
        lines.append("- **Languages**: not detected")

    if scan.framework_hints:
        lines.append(f"- **Frameworks**: {', '.join(scan.framework_hints)}")

    if scan.file_counts:
        counts_str = ", ".join(
            f"{lang} ({n})" for lang, n in sorted(scan.file_counts.items(), key=lambda x: -x[1])
        )
        lines.append(f"- **File counts**: {counts_str}")

    if scan.config_files:
        lines.append(f"- **Config files**: {', '.join(sorted(scan.config_files))}")

    if not lines:
        lines.append("Stack not detected — see detection notes.")

    return "\n".join(lines)


def _render_top_level(scan: RepoScan) -> str:
    if not scan.top_level_dirs:
        return "No top-level directories detected."
    lines = [f"- `{d}/`" for d in sorted(scan.top_level_dirs)]
    return "\n".join(lines)


def _render_key_locations(scan: RepoScan) -> str:
    lines: list[str] = []

    if scan.source_dirs:
        lines.append(f"- **Source**: {', '.join(f'`{d}/`' for d in scan.source_dirs)}")
    else:
        lines.append("- **Source**: not clearly identified (may be at repo root)")

    if scan.test_dirs:
        lines.append(f"- **Tests**: {', '.join(f'`{d}/`' for d in scan.test_dirs)}")
    else:
        lines.append("- **Tests**: not detected")

    if scan.docs_dirs:
        lines.append(f"- **Docs**: {', '.join(f'`{d}/`' for d in scan.docs_dirs)}")
    else:
        lines.append("- **Docs**: not detected")

    if scan.readme_path:
        lines.append(f"- **README**: `{scan.readme_path}`")

    return "\n".join(lines)


def _render_starting_points(scan: RepoScan) -> str:
    points: list[str] = []

    if scan.readme_path:
        points.append(f"`{scan.readme_path}` — project overview")

    for f in scan.config_files:
        if f in ("pyproject.toml", "package.json", "go.mod", "Cargo.toml", "pom.xml"):
            points.append(f"`{f}` — dependencies and project metadata")
            break

    for d in scan.source_dirs[:2]:
        points.append(f"`{d}/` — main source code")

    for d in scan.test_dirs[:1]:
        points.append(f"`{d}/` — test suite")

    if not points:
        points.append("Explore the top-level directories listed above.")

    return "\n".join(f"- {p}" for p in points)


def _render_notes(notes: list[str]) -> str:
    return "\n".join(f"- {n}" for n in notes)


# ---------------------------------------------------------------------------
# Section renderers — architecture.md
# ---------------------------------------------------------------------------


def _render_boundaries(scan: RepoScan) -> str:
    """Describe major code boundaries based on directory structure."""
    boundaries: list[str] = []

    if scan.source_dirs:
        for d in scan.source_dirs:
            boundaries.append(f"- **`{d}/`** — production source code")

    if scan.test_dirs:
        for d in scan.test_dirs:
            boundaries.append(f"- **`{d}/`** — test suite (separate from production code)")

    if scan.docs_dirs:
        for d in scan.docs_dirs:
            boundaries.append(f"- **`{d}/`** — documentation")

    # Monorepo signal: multiple conventional dirs
    apps_dirs = [d for d in scan.top_level_dirs if d.lower() in ("apps", "packages", "services")]
    if apps_dirs:
        for d in apps_dirs:
            boundaries.append(f"- **`{d}/`** — multiple apps/packages (possible monorepo)")

    if not boundaries:
        boundaries.append(
            "- No clear boundaries detected. "
            "The codebase may be structured at the root level."
        )

    return "\n".join(boundaries)


def _render_layout(scan: RepoScan) -> str:
    """Infer and describe the high-level architectural layout."""
    lines: list[str] = []

    # Monorepo
    if any(d.lower() in ("apps", "packages", "services") for d in scan.top_level_dirs):
        lines.append("**Pattern**: Monorepo (multiple apps or packages in one repo)")
    elif scan.source_dirs:
        lines.append("**Pattern**: Single-application repo with dedicated source directory")
    else:
        lines.append("**Pattern**: Flat or non-standard layout")

    # Framework-specific layout hints
    if "Django" in scan.framework_hints:
        lines.append("**Django layout**: expect apps as subdirectories, `settings.py`, `urls.py`")
    if "FastAPI" in scan.framework_hints:
        lines.append("**FastAPI layout**: expect `main.py` / `app.py`, routers, models, schemas")
    if "Next.js" in scan.framework_hints:
        lines.append("**Next.js layout**: expect `pages/` or `app/`, `public/`, `components/`")
    if "React" in scan.framework_hints and "Next.js" not in scan.framework_hints:
        lines.append("**React layout**: expect `src/components/`, `src/hooks/`, `src/pages/`")

    if not lines:
        lines.append("Layout could not be confidently inferred from directory structure alone.")

    return "\n".join(lines)


def _render_coupling_notes(scan: RepoScan) -> str:
    """Surface coupling or ambiguity worth flagging."""
    notes: list[str] = []

    if len(scan.languages) > 3:
        notes.append(
            f"Multi-language repo ({', '.join(scan.languages)}). "
            "Check language boundaries before refactoring."
        )

    if not scan.test_dirs:
        notes.append(
            "No test directory detected. Test coverage is unknown — be cautious with changes."
        )

    if scan.confidence < 0.7:
        notes.append(
            f"Low-confidence scan ({scan.confidence:.0%}). "
            "Structural signals were weak; verify key locations manually."
        )

    # Pass through any scanner-generated notes
    for note in scan.notes:
        if note not in notes:
            notes.append(note)

    return "\n".join(f"- {n}" for n in notes) if notes else ""


def _render_inspect_first(scan: RepoScan) -> str:
    """Files/dirs worth looking at first when starting a task."""
    items: list[str] = []

    for d in scan.source_dirs[:3]:
        items.append(f"`{d}/` — main source code")

    for cfg in ("pyproject.toml", "package.json", "go.mod", "Cargo.toml"):
        if cfg in scan.config_files:
            items.append(f"`{cfg}` — project metadata and dependencies")
            break

    if scan.readme_path:
        items.append(f"`{scan.readme_path}` — project intent and setup")

    for d in scan.test_dirs[:1]:
        items.append(f"`{d}/` — to understand expected behaviour")

    if not items:
        items.append("No strong starting points detected — explore top-level directories.")

    return "\n".join(f"- {i}" for i in items)
