"""Memory artifact generator for the memory subsystem.

Turns structured scan/model data into human- and agent-readable markdown.
This module produces *content strings only* — it never writes to disk.
All disk I/O is handled by ``writer.py``.

Design constraints
------------------
- Deterministic: same inputs always produce the same string.
- Concise: optimised for agent context windows, not human prose.
- Graceful degradation: produces useful output even when signals are weak.
- No LLM calls: all generation is template/heuristic-driven.

Public API
----------
generate_repo_summary(scan)                        -> str  (content for repo.md)
generate_architecture_doc(scan)                    -> str  (content for architecture.md)
generate_feature_doc(feature)                      -> str  (content for features/<slug>.md)
generate_module_doc(module)                        -> str  (content for modules/<slug>.md)
generate_conventions_doc(scan, overrides)          -> str  (content for rules/conventions.md)
generate_safe_boundaries_doc(scan, overrides)      -> str  (content for rules/safe-boundaries.md)
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from .models import FeatureMemory, ModuleMemory
from .scanner import RepoScan
from .writer import render_markdown_section

if TYPE_CHECKING:
    from .graph_bridge import FileNodeSummary
    from .overrides import Overrides

# Shared preamble for auto-generated files
_AUTO_GENERATED_NOTE = (
    "> Auto-generated by repo-memory. "
    "Add corrections in `.agent-memory/overrides/`."
)

# Max files to list in a section before truncating
_MAX_FILES_LISTED = 20

# ---------------------------------------------------------------------------
# repo.md
# ---------------------------------------------------------------------------

_REPO_PREAMBLE = (
    "> This file is auto-generated by repo-memory. "
    "Edit `.agent-memory/overrides/` to add human corrections."
)


def generate_repo_summary(scan: RepoScan) -> str:
    """Generate content for ``.agent-memory/repo.md``.

    Args:
        scan: A populated :class:`~scanner.RepoScan`.

    Returns:
        Markdown string suitable for writing directly to ``repo.md``.
    """
    sections: list[str] = []

    # H1 title
    repo_name = scan.repo_root.name or "this-repo"
    sections.append(f"# Repo: {repo_name}\n\n{_REPO_PREAMBLE}")

    # Purpose / stack
    sections.append(render_markdown_section(
        "Stack",
        _render_stack(scan),
    ))

    # Top-level structure
    sections.append(render_markdown_section(
        "Top-level structure",
        _render_top_level(scan),
    ))

    # Where things live
    sections.append(render_markdown_section(
        "Key locations",
        _render_key_locations(scan),
    ))

    # Starting points
    sections.append(render_markdown_section(
        "Suggested starting points",
        _render_starting_points(scan),
    ))

    # Ambiguity notes
    if scan.notes:
        sections.append(render_markdown_section(
            "Detection notes",
            _render_notes(scan.notes),
        ))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# architecture.md
# ---------------------------------------------------------------------------

_ARCH_PREAMBLE = (
    "> Auto-generated architectural overview. "
    "Confidence: {confidence:.0%}. "
    "Add corrections in `.agent-memory/overrides/`."
)


def generate_architecture_doc(scan: RepoScan) -> str:
    """Generate content for ``.agent-memory/architecture.md``.

    Args:
        scan: A populated :class:`~scanner.RepoScan`.

    Returns:
        Markdown string suitable for writing directly to ``architecture.md``.
    """
    sections: list[str] = []

    repo_name = scan.repo_root.name or "this-repo"
    preamble = _ARCH_PREAMBLE.format(confidence=scan.confidence)
    sections.append(f"# Architecture: {repo_name}\n\n{preamble}")

    # Major boundaries
    sections.append(render_markdown_section(
        "Major boundaries",
        _render_boundaries(scan),
    ))

    # Architectural layout
    sections.append(render_markdown_section(
        "Inferred layout",
        _render_layout(scan),
    ))

    # Coupling / ambiguity
    coupling = _render_coupling_notes(scan)
    if coupling:
        sections.append(render_markdown_section(
            "Coupling and ambiguity notes",
            coupling,
        ))

    # Inspect first
    sections.append(render_markdown_section(
        "Inspect first",
        _render_inspect_first(scan),
    ))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# Section renderers — repo.md
# ---------------------------------------------------------------------------


def _render_stack(scan: RepoScan) -> str:
    lines: list[str] = []

    if scan.languages:
        lines.append(f"- **Languages**: {', '.join(scan.languages)}")
    else:
        lines.append("- **Languages**: not detected")

    if scan.framework_hints:
        lines.append(f"- **Frameworks**: {', '.join(scan.framework_hints)}")

    if scan.file_counts:
        counts_str = ", ".join(
            f"{lang} ({n})" for lang, n in sorted(scan.file_counts.items(), key=lambda x: -x[1])
        )
        lines.append(f"- **File counts**: {counts_str}")

    if scan.config_files:
        lines.append(f"- **Config files**: {', '.join(sorted(scan.config_files))}")

    if not lines:
        lines.append("Stack not detected — see detection notes.")

    return "\n".join(lines)


def _render_top_level(scan: RepoScan) -> str:
    if not scan.top_level_dirs:
        return "No top-level directories detected."
    lines = [f"- `{d}/`" for d in sorted(scan.top_level_dirs)]
    return "\n".join(lines)


def _render_key_locations(scan: RepoScan) -> str:
    lines: list[str] = []

    if scan.source_dirs:
        lines.append(f"- **Source**: {', '.join(f'`{d}/`' for d in scan.source_dirs)}")
    else:
        lines.append("- **Source**: not clearly identified (may be at repo root)")

    if scan.test_dirs:
        lines.append(f"- **Tests**: {', '.join(f'`{d}/`' for d in scan.test_dirs)}")
    else:
        lines.append("- **Tests**: not detected")

    if scan.docs_dirs:
        lines.append(f"- **Docs**: {', '.join(f'`{d}/`' for d in scan.docs_dirs)}")
    else:
        lines.append("- **Docs**: not detected")

    if scan.readme_path:
        lines.append(f"- **README**: `{scan.readme_path}`")

    return "\n".join(lines)


def _render_starting_points(scan: RepoScan) -> str:
    points: list[str] = []

    if scan.readme_path:
        points.append(f"`{scan.readme_path}` — project overview")

    for f in scan.config_files:
        if f in ("pyproject.toml", "package.json", "go.mod", "Cargo.toml", "pom.xml"):
            points.append(f"`{f}` — dependencies and project metadata")
            break

    for d in scan.source_dirs[:2]:
        points.append(f"`{d}/` — main source code")

    for d in scan.test_dirs[:1]:
        points.append(f"`{d}/` — test suite")

    if not points:
        points.append("Explore the top-level directories listed above.")

    return "\n".join(f"- {p}" for p in points)


def _render_notes(notes: list[str]) -> str:
    return "\n".join(f"- {n}" for n in notes)


# ---------------------------------------------------------------------------
# Section renderers — architecture.md
# ---------------------------------------------------------------------------


def _render_boundaries(scan: RepoScan) -> str:
    """Describe major code boundaries based on directory structure."""
    boundaries: list[str] = []

    if scan.source_dirs:
        for d in scan.source_dirs:
            boundaries.append(f"- **`{d}/`** — production source code")

    if scan.test_dirs:
        for d in scan.test_dirs:
            boundaries.append(f"- **`{d}/`** — test suite (separate from production code)")

    if scan.docs_dirs:
        for d in scan.docs_dirs:
            boundaries.append(f"- **`{d}/`** — documentation")

    # Monorepo signal: multiple conventional dirs
    apps_dirs = [d for d in scan.top_level_dirs if d.lower() in ("apps", "packages", "services")]
    if apps_dirs:
        for d in apps_dirs:
            boundaries.append(f"- **`{d}/`** — multiple apps/packages (possible monorepo)")

    if not boundaries:
        boundaries.append(
            "- No clear boundaries detected. "
            "The codebase may be structured at the root level."
        )

    return "\n".join(boundaries)


def _render_layout(scan: RepoScan) -> str:
    """Infer and describe the high-level architectural layout."""
    lines: list[str] = []

    # Monorepo
    if any(d.lower() in ("apps", "packages", "services") for d in scan.top_level_dirs):
        lines.append("**Pattern**: Monorepo (multiple apps or packages in one repo)")
    elif scan.source_dirs:
        lines.append("**Pattern**: Single-application repo with dedicated source directory")
    else:
        lines.append("**Pattern**: Flat or non-standard layout")

    # Framework-specific layout hints
    if "Django" in scan.framework_hints:
        lines.append("**Django layout**: expect apps as subdirectories, `settings.py`, `urls.py`")
    if "FastAPI" in scan.framework_hints:
        lines.append("**FastAPI layout**: expect `main.py` / `app.py`, routers, models, schemas")
    if "Next.js" in scan.framework_hints:
        lines.append("**Next.js layout**: expect `pages/` or `app/`, `public/`, `components/`")
    if "React" in scan.framework_hints and "Next.js" not in scan.framework_hints:
        lines.append("**React layout**: expect `src/components/`, `src/hooks/`, `src/pages/`")

    if not lines:
        lines.append("Layout could not be confidently inferred from directory structure alone.")

    return "\n".join(lines)


def _render_coupling_notes(scan: RepoScan) -> str:
    """Surface coupling or ambiguity worth flagging."""
    notes: list[str] = []

    if len(scan.languages) > 3:
        notes.append(
            f"Multi-language repo ({', '.join(scan.languages)}). "
            "Check language boundaries before refactoring."
        )

    if not scan.test_dirs:
        notes.append(
            "No test directory detected. Test coverage is unknown — be cautious with changes."
        )

    if scan.confidence < 0.7:
        notes.append(
            f"Low-confidence scan ({scan.confidence:.0%}). "
            "Structural signals were weak; verify key locations manually."
        )

    # Pass through any scanner-generated notes
    for note in scan.notes:
        if note not in notes:
            notes.append(note)

    return "\n".join(f"- {n}" for n in notes) if notes else ""


def _render_inspect_first(scan: RepoScan) -> str:
    """Files/dirs worth looking at first when starting a task."""
    items: list[str] = []

    for d in scan.source_dirs[:3]:
        items.append(f"`{d}/` — main source code")

    for cfg in ("pyproject.toml", "package.json", "go.mod", "Cargo.toml"):
        if cfg in scan.config_files:
            items.append(f"`{cfg}` — project metadata and dependencies")
            break

    if scan.readme_path:
        items.append(f"`{scan.readme_path}` — project intent and setup")

    for d in scan.test_dirs[:1]:
        items.append(f"`{d}/` — to understand expected behaviour")

    if not items:
        items.append("No strong starting points detected — explore top-level directories.")

    return "\n".join(f"- {i}" for i in items)


# ---------------------------------------------------------------------------
# features/<slug>.md
# ---------------------------------------------------------------------------


def generate_feature_doc(
    feature: FeatureMemory,
    vocabulary: dict[str, list[str]] | None = None,
    node_summaries: "dict[str, FileNodeSummary] | None" = None,
) -> str:
    """Generate content for ``.agent-memory/features/<slug>.md``.

    Args:
        feature:        A classified :class:`~models.FeatureMemory` instance.
        vocabulary:     Optional dict of file_path → symbol names from the graph.
                        Used for responsibility inference and key symbol listing.
        node_summaries: Optional dict of file_path → :class:`FileNodeSummary`.
                        When present, purpose statements are grounded in actual
                        class/function names rather than inferred from file stems.

    Returns:
        Markdown string ready to be written to disk by ``writer.py``.
    """
    sections: list[str] = []

    # Header
    confidence_note = _confidence_label(feature.confidence)
    sections.append(
        f"# Feature: {feature.name}\n\n"
        f"{_AUTO_GENERATED_NOTE}\n\n"
        f"**Confidence**: {feature.confidence:.0%} ({confidence_note})"
    )

    # Purpose — grounded in actual symbols when graph data is available
    sections.append(render_markdown_section(
        "Purpose",
        _feature_purpose(feature, vocabulary=vocabulary, node_summaries=node_summaries),
    ))

    # Main files
    sections.append(render_markdown_section(
        "Main files",
        _render_file_list(feature.files, "No source files detected."),
    ))

    # Key symbols — from graph vocabulary (function/class names)
    if vocabulary:
        key_symbols = _top_symbols(vocabulary, feature.files)
        if key_symbols:
            sections.append(render_markdown_section(
                "Key symbols",
                ", ".join(f"`{s}`" for s in key_symbols),
            ))

    # Likely entry points — stem matching + vocabulary-aware detection
    entry_points = _infer_entry_points(feature.files, vocabulary=vocabulary)
    if entry_points:
        sections.append(render_markdown_section(
            "Likely entry points",
            _render_file_list(entry_points, ""),
        ))

    # Related tests
    sections.append(render_markdown_section(
        "Related tests",
        _render_file_list(feature.tests, "No related tests detected."),
    ))

    # Neighboring areas — other features that share files (populated by caller
    # in future; for now use dependencies field)
    if feature.dependencies:
        sections.append(render_markdown_section(
            "Neighboring areas",
            "\n".join(f"- {d}" for d in sorted(feature.dependencies)),
        ))

    # Warnings / ambiguity
    warnings = _feature_warnings(feature)
    if warnings:
        sections.append(render_markdown_section(
            "Warnings and notes",
            warnings,
        ))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# modules/<slug>.md
# ---------------------------------------------------------------------------


def generate_module_doc(
    module: ModuleMemory,
    vocabulary: dict[str, list[str]] | None = None,
    node_summaries: "dict[str, FileNodeSummary] | None" = None,
) -> str:
    """Generate content for ``.agent-memory/modules/<slug>.md``.

    Args:
        module:         A classified :class:`~models.ModuleMemory` instance.
        vocabulary:     Optional dict of file_path → symbol names from the graph.
                        Used for responsibility inference and key symbol listing.
        node_summaries: Optional dict of file_path → :class:`FileNodeSummary`.
                        When present, purpose statements are grounded in actual
                        class/function names rather than inferred from file stems.

    Returns:
        Markdown string ready to be written to disk by ``writer.py``.
    """
    sections: list[str] = []

    # Header
    confidence_note = _confidence_label(module.confidence)
    sections.append(
        f"# Module: {module.name}\n\n"
        f"{_AUTO_GENERATED_NOTE}\n\n"
        f"**Confidence**: {module.confidence:.0%} ({confidence_note})"
    )

    # Purpose — grounded in actual symbols when graph data is available
    sections.append(render_markdown_section(
        "Purpose",
        _module_purpose(module, vocabulary=vocabulary, node_summaries=node_summaries),
    ))

    # Responsibilities — from graph vocabulary first, file stems as fallback
    responsibilities = _infer_responsibilities(module.files, vocabulary=vocabulary)
    if responsibilities:
        sections.append(render_markdown_section(
            "Responsibilities",
            "\n".join(f"- {r}" for r in responsibilities),
        ))

    # Key symbols — from graph vocabulary (function/class names)
    if vocabulary:
        key_symbols = _top_symbols(vocabulary, module.files)
        if key_symbols:
            sections.append(render_markdown_section(
                "Key symbols",
                ", ".join(f"`{s}`" for s in key_symbols),
            ))

    # Files
    sections.append(render_markdown_section(
        "Files",
        _render_file_list(module.files, "No source files detected."),
    ))

    # Dependencies
    if module.dependencies:
        sections.append(render_markdown_section(
            "Dependencies",
            "\n".join(f"- `{d}`" for d in sorted(module.dependencies)),
        ))

    # Dependents
    if module.dependents:
        sections.append(render_markdown_section(
            "Depended on by",
            "\n".join(f"- `{d}`" for d in sorted(module.dependents)),
        ))

    # Related tests
    sections.append(render_markdown_section(
        "Related tests",
        _render_file_list(module.tests, "No related tests detected."),
    ))

    # Risk / coupling notes
    risks = _module_risks(module)
    if risks:
        sections.append(render_markdown_section(
            "Risk and coupling notes",
            risks,
        ))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# Feature doc helpers
# ---------------------------------------------------------------------------


def _feature_purpose(
    feature: FeatureMemory,
    vocabulary: dict[str, list[str]] | None = None,
    node_summaries: "dict[str, FileNodeSummary] | None" = None,
) -> str:
    """Produce a purpose statement for a feature doc.

    Priority:
    1. node_summaries present → class/function names separated, most informative.
    2. vocabulary present → flat top symbols, still graph-grounded.
    3. Fallback → path/name heuristic only.
    """
    name = feature.name
    if node_summaries:
        classes, functions = _collect_symbols_from_summaries(node_summaries, feature.files)
        if classes or functions:
            return _format_purpose_with_symbols(
                f"Implements the **{name}** product area", classes, functions
            )
    if vocabulary:
        top_syms = _top_symbols(vocabulary, feature.files, max_total=5)
        if top_syms:
            sym_str = ", ".join(f"`{s}`" for s in top_syms)
            return f"Implements the **{name}** product area. Key symbols: {sym_str}."
    source = _classification_source(feature.confidence)
    return (
        f"Implements the **{name}** product area "
        f"({len(feature.files)} file(s) detected; classified by {source})."
    )


def _feature_warnings(feature: FeatureMemory) -> str:
    """Return warning lines for a feature doc."""
    lines: list[str] = []
    if feature.confidence < 0.6:
        lines.append(
            f"Low confidence ({feature.confidence:.0%}): grouping is inferred from "
            "directory structure only — verify file membership manually."
        )
    if not feature.tests:
        lines.append("No test files linked to this feature. Coverage is unknown.")
    if len(feature.files) > _MAX_FILES_LISTED:
        lines.append(
            f"Large feature: {len(feature.files)} files total "
            f"(only first {_MAX_FILES_LISTED} shown above). "
            "Consider splitting into sub-features."
        )
    return "\n".join(f"- {line}" for line in lines)


# File stems strongly associated with entry points
_ENTRY_POINT_STEMS = frozenset({
    "main", "app", "index", "server", "router", "routes",
    "views", "view", "controller", "controllers", "handler", "handlers",
    "api", "endpoint", "endpoints",
})

# Symbol name tokens that suggest an entry point function/class
_ENTRY_POINT_SYM_TOKENS = frozenset({
    "handle", "execute", "run", "process", "dispatch",
    "serve", "setup", "create_app", "make_app",
})


def _infer_entry_points(
    files: list[str],
    vocabulary: dict[str, list[str]] | None = None,
) -> list[str]:
    """Return files likely to be entry points.

    Strategy 1 (always): file stem matching against known entry-point names.
    Strategy 2 (with vocabulary): files that define symbols with entry-point
    token names (e.g. ``handle_request``, ``run_server``), catching files
    whose stems don't match but whose content clearly acts as an entry point.
    """
    result: set[str] = {f for f in files if Path(f).stem.lower() in _ENTRY_POINT_STEMS}

    if vocabulary:
        for f in files:
            if f in result:
                continue
            for sym in vocabulary.get(f, []):
                sym_lower = sym.lower()
                if any(token in sym_lower for token in _ENTRY_POINT_SYM_TOKENS):
                    result.add(f)
                    break

    return sorted(result)[:5]


# ---------------------------------------------------------------------------
# Shared symbol helpers (used by both feature and module purpose statements)
# ---------------------------------------------------------------------------


def _collect_symbols_from_summaries(
    node_summaries: "dict[str, FileNodeSummary]",
    files: list[str],
    max_classes: int = 3,
    max_functions: int = 3,
) -> "tuple[list[str], list[str]]":
    """Return deduplicated (classes, functions) lists across *files*.

    Iterates over each file's :class:`~graph_bridge.FileNodeSummary`, collecting
    class and function names in file order.  Deduplicates across files so the
    same name does not appear twice.  Caps at *max_classes* / *max_functions*.
    """
    seen: set[str] = set()
    classes: list[str] = []
    functions: list[str] = []
    for fp in files:
        ns = node_summaries.get(fp)
        if ns is None:
            continue
        for c in ns.classes:
            if c not in seen:
                seen.add(c)
                classes.append(c)
        for f in ns.functions:
            if f not in seen:
                seen.add(f)
                functions.append(f)
    return classes[:max_classes], functions[:max_functions]


def _format_purpose_with_symbols(
    prefix: str,
    classes: list[str],
    functions: list[str],
) -> str:
    """Compose a purpose statement from separated class and function names.

    Produces output like:
        "Implements the **auth** product area. Defines ``AuthMiddleware``;
         provides ``verify_token``, ``login_required``."
    """
    if classes and functions:
        cls_str = ", ".join(f"`{c}`" for c in classes)
        fn_str = ", ".join(f"`{f}`" for f in functions)
        return f"{prefix}. Defines {cls_str}; provides {fn_str}."
    elif classes:
        cls_str = ", ".join(f"`{c}`" for c in classes)
        return f"{prefix}. Defines {cls_str}."
    else:
        fn_str = ", ".join(f"`{f}`" for f in functions)
        return f"{prefix}. Provides {fn_str}."


# ---------------------------------------------------------------------------
# Module doc helpers
# ---------------------------------------------------------------------------


def _module_purpose(
    module: ModuleMemory,
    vocabulary: dict[str, list[str]] | None = None,
    node_summaries: "dict[str, FileNodeSummary] | None" = None,
) -> str:
    """Produce a purpose statement for a module doc.

    Priority:
    1. node_summaries present → class/function names separated, most informative.
    2. vocabulary present → flat top symbols, still graph-grounded.
    3. Fallback → path/name heuristic only.
    """
    name = module.name
    if node_summaries:
        classes, functions = _collect_symbols_from_summaries(node_summaries, module.files)
        if classes or functions:
            return _format_purpose_with_symbols(
                f"Provides the **{name}** package", classes, functions
            )
    if vocabulary:
        top_syms = _top_symbols(vocabulary, module.files, max_total=5)
        if top_syms:
            sym_str = ", ".join(f"`{s}`" for s in top_syms)
            return f"Provides the **{name}** package. Key symbols: {sym_str}."
    source = _classification_source(module.confidence)
    return (
        f"Provides the **{name}** package/module boundary "
        f"({len(module.files)} file(s); classified by {source})."
    )


def _infer_responsibilities(
    files: list[str],
    vocabulary: dict[str, list[str]] | None = None,
) -> list[str]:
    """Infer likely responsibilities, using graph vocabulary when available.

    Strategy:
    1. If *vocabulary* is provided (function/class names from graph.db), map
       symbol name tokens to semantic domains.  This produces accurate labels
       like "authentication and token management" instead of guessing from
       file stems.
    2. Fall back to file-stem heuristics when vocabulary is absent or empty.
    """
    if vocabulary:
        vocab_result = _responsibilities_from_vocabulary(vocabulary, files)
        if vocab_result:
            return vocab_result[:6]

    # Fallback: stem-based heuristics
    stem_hints: dict[str, str] = {
        "models": "data models / ORM definitions",
        "model": "data model definitions",
        "views": "view / template rendering",
        "view": "view / template rendering",
        "routes": "URL routing / endpoint registration",
        "router": "request routing",
        "controller": "request handling / business dispatch",
        "controllers": "request handling / business dispatch",
        "service": "business logic / service layer",
        "services": "business logic / service layer",
        "middleware": "request/response middleware",
        "schema": "data schema / validation",
        "schemas": "data schema / validation",
        "serializer": "data serialisation",
        "serializers": "data serialisation",
        "utils": "shared utilities / helpers",
        "helpers": "shared helper functions",
        "config": "configuration management",
        "settings": "application settings",
        "migrations": "database schema migrations",
        "tasks": "background task definitions",
        "worker": "background worker / job processing",
        "client": "external API / service client",
        "main": "application entrypoint",
        "app": "application setup / factory",
        "index": "module public interface",
        "types": "type definitions / interfaces",
        "interfaces": "interface / contract definitions",
    }
    found: list[str] = []
    seen: set[str] = set()
    for f in sorted(files):
        stem = Path(f).stem.lower()
        if stem in stem_hints and stem_hints[stem] not in seen:
            found.append(stem_hints[stem])
            seen.add(stem_hints[stem])
    return found[:6]


def _responsibilities_from_vocabulary(
    vocabulary: dict[str, list[str]],
    files: list[str],
) -> list[str]:
    """Derive responsibility labels from actual function/class names in the graph.

    Maps symbol name tokens to semantic domains using a keyword→domain table.
    Multiple symbols mapping to the same domain collapse into one label.
    """
    # keyword token → human label  (longest/most-specific match wins implicitly)
    _DOMAIN_KEYWORDS: list[tuple[tuple[str, ...], str]] = [
        (("auth", "authenticat", "login", "logout", "session", "credential", "permission", "jwt", "token", "oauth"), "authentication and authorisation"),
        (("payment", "billing", "invoice", "charge", "stripe", "subscription", "price", "checkout"), "payments and billing"),
        (("user", "account", "profile", "signup", "register", "password", "email"), "user management"),
        (("notif", "email", "sms", "push", "webhook", "alert", "message", "send"), "notifications and messaging"),
        (("route", "endpoint", "controller", "handler", "view", "api", "request", "response", "middleware"), "request handling and routing"),
        (("model", "schema", "orm", "database", "db", "query", "migration", "entity", "record"), "data models and persistence"),
        (("cache", "redis", "memcache", "ttl", "invalidat"), "caching"),
        (("task", "job", "worker", "queue", "celery", "async", "background", "schedule"), "background jobs and task processing"),
        (("test", "mock", "fixture", "assert", "expect", "spec"), "test utilities"),
        (("config", "setting", "env", "constant", "flag", "feature"), "configuration"),
        (("util", "helper", "common", "shared", "format", "parse", "convert", "transform"), "shared utilities"),
        (("log", "trace", "metric", "monitor", "telemetry", "observ"), "observability and logging"),
        (("upload", "file", "storage", "s3", "blob", "media", "image"), "file and media handling"),
        (("search", "index", "elastic", "solr", "query", "filter", "sort"), "search and indexing"),
        (("graph", "node", "edge", "tree", "traverse", "bfs", "dfs"), "graph and tree operations"),
        (("render", "template", "component", "view", "html", "jsx", "tsx", "style"), "UI rendering"),
        (("import", "export", "parser", "lexer", "ast", "transpil", "compil"), "parsing and compilation"),
        (("rate", "limit", "throttle", "quota", "bucket"), "rate limiting and throttling"),
        (("encrypt", "decrypt", "hash", "sign", "verify", "ssl", "tls", "crypto"), "cryptography and security"),
        (("websocket", "socket", "stream", "event", "pubsub", "channel"), "real-time and streaming"),
    ]

    # Collect all symbol names across relevant files
    all_symbols: list[str] = []
    for fp in files:
        all_symbols.extend(vocabulary.get(fp, []))

    if not all_symbols:
        return []

    # For each symbol, check which domain keywords appear in its name
    matched_domains: dict[str, int] = {}  # domain -> match count
    for symbol in all_symbols:
        sym_lower = symbol.lower()
        for keywords, domain in _DOMAIN_KEYWORDS:
            if any(kw in sym_lower for kw in keywords):
                matched_domains[domain] = matched_domains.get(domain, 0) + 1

    # Return domains sorted by match count (most-evidenced first)
    return [d for d, _ in sorted(matched_domains.items(), key=lambda x: -x[1])]


def _top_symbols(vocabulary: dict[str, list[str]], files: list[str], max_total: int = 12) -> list[str]:
    """Return the most representative symbol names across *files*.

    Picks up to *max_total* names, preferring shorter names (more likely to be
    meaningful public API) and deduplicating.
    """
    seen: set[str] = set()
    symbols: list[str] = []
    for fp in files:
        for name in vocabulary.get(fp, []):
            if name not in seen:
                seen.add(name)
                symbols.append(name)
    # Prefer shorter names (public API) over long internal names
    symbols.sort(key=lambda s: (len(s), s))
    return symbols[:max_total]


def _module_risks(module: ModuleMemory) -> str:
    """Return risk/coupling notes for a module doc."""
    lines: list[str] = []
    if module.confidence < 0.6:
        lines.append(
            f"Low confidence ({module.confidence:.0%}): boundary was inferred, "
            "not derived from explicit package structure."
        )
    if len(module.files) > _MAX_FILES_LISTED:
        lines.append(
            f"Large module: {len(module.files)} files. "
            "High file count may indicate coupling or missed sub-module boundaries."
        )
    if module.dependents:
        lines.append(
            f"This module is depended on by {len(module.dependents)} other module(s): "
            f"{', '.join(sorted(module.dependents)[:3])}. "
            "Changes here have broad impact."
        )
    return "\n".join(f"- {line}" for line in lines)


# ---------------------------------------------------------------------------
# Shared rendering helpers
# ---------------------------------------------------------------------------


def _render_file_list(files: list[str], empty_msg: str) -> str:
    """Render a sorted list of files as markdown bullets, truncating if large."""
    if not files:
        return empty_msg
    shown = sorted(files)[:_MAX_FILES_LISTED]
    lines = [f"- `{f}`" for f in shown]
    if len(files) > _MAX_FILES_LISTED:
        lines.append(f"- _…and {len(files) - _MAX_FILES_LISTED} more_")
    return "\n".join(lines)


def _confidence_label(confidence: float) -> str:
    if confidence >= 0.85:
        return "high — derived from explicit package structure"
    if confidence >= 0.65:
        return "medium — inferred from directory naming"
    return "low — heuristic grouping, verify manually"


def _classification_source(confidence: float) -> str:
    if confidence >= 0.85:
        return "explicit package boundary"
    if confidence >= 0.65:
        return "directory name heuristic"
    return "weak heuristic (low confidence)"


# ---------------------------------------------------------------------------
# rules/conventions.md
# ---------------------------------------------------------------------------

# Inferred language-level conventions
_LANG_CONVENTIONS: dict[str, list[str]] = {
    "python": [
        "Follow PEP 8 style (4-space indent, max 79–100 chars per line).",
        "Use type annotations on all public functions.",
        "Prefer `pathlib.Path` over `os.path` for file operations.",
    ],
    "typescript": [
        "Use strict TypeScript (`strict: true` in tsconfig).",
        "Prefer `interface` over `type` for object shapes.",
        "Avoid `any`; use `unknown` and narrow explicitly.",
    ],
    "javascript": [
        "Prefer `const` over `let`; avoid `var`.",
        "Use ES modules (`import`/`export`) over CommonJS.",
    ],
    "go": [
        "Return errors explicitly; never ignore them.",
        "Keep package names short and lowercase.",
        "Use `gofmt` formatting.",
    ],
    "rust": [
        "Handle `Result` and `Option` explicitly — no `unwrap()` in production paths.",
        "Prefer owned types unless sharing is necessary.",
    ],
    "java": [
        "Follow Google Java Style Guide.",
        "Prefer composition over inheritance.",
    ],
}

# Inferred framework-level conventions
_FRAMEWORK_CONVENTIONS: dict[str, list[str]] = {
    "Django": [
        "Keep business logic in services, not views.",
        "Manage schema changes via `makemigrations` — never edit migrations manually.",
    ],
    "FastAPI": [
        "Use Pydantic schemas for all request/response bodies.",
        "Register routers in `main.py` or `app.py`.",
    ],
    "React": [
        "Keep components small and single-purpose.",
        "Lift shared state up to the nearest common ancestor.",
    ],
    "Next.js": [
        "Prefer server components over client components for data fetching.",
        "Use `app/` directory structure for Next.js 13+.",
    ],
}

# Paths that are almost universally never-edit
_INFERRED_NEVER_EDIT: list[str] = [
    "node_modules/",
    ".git/",
    "__pycache__/",
    "*.min.js",
    "*.min.css",
    "dist/",
    "build/",
    ".venv/",
    "venv/",
]


def generate_conventions_doc(scan: RepoScan, overrides: Overrides | None = None) -> str:
    """Generate content for ``.agent-memory/rules/conventions.md``.

    Combines inferred language/framework conventions with human notes from
    override files. Human notes are always included verbatim at the top.

    Args:
        scan:      A populated :class:`~scanner.RepoScan`.
        overrides: Optional loaded :class:`~overrides.Overrides`; ``None``
                   produces inference-only output.

    Returns:
        Markdown string suitable for writing to ``rules/conventions.md``.
    """
    sections: list[str] = []

    repo_name = scan.repo_root.name or "this-repo"
    sections.append(
        f"# Conventions: {repo_name}\n\n"
        f"{_AUTO_GENERATED_NOTE}"
    )

    # Human notes first — they are authoritative
    if overrides and overrides.notes:
        notes_body = "\n".join(f"- {n}" for n in overrides.notes)
        sections.append(render_markdown_section("Team notes", notes_body))

    # Language conventions
    lang_lines: list[str] = []
    for lang in sorted(scan.languages):
        for rule in _LANG_CONVENTIONS.get(lang, []):
            lang_lines.append(f"- **{lang}**: {rule}")
    if lang_lines:
        sections.append(render_markdown_section("Language conventions", "\n".join(lang_lines)))

    # Framework conventions
    fw_lines: list[str] = []
    for fw in sorted(scan.framework_hints):
        for rule in _FRAMEWORK_CONVENTIONS.get(fw, []):
            fw_lines.append(f"- **{fw}**: {rule}")
    if fw_lines:
        sections.append(render_markdown_section("Framework conventions", "\n".join(fw_lines)))

    # Project-level conventions inferred from scan signals
    inferred = _infer_project_conventions(scan)
    if inferred:
        sections.append(render_markdown_section(
            "Inferred project patterns",
            "\n".join(f"- {c}" for c in inferred),
        ))

    if len(sections) == 1:
        sections.append(
            "> No conventions detected. "
            "Add notes in `.agent-memory/overrides/global.yaml` to guide Claude Code."
        )

    return "\n\n".join(sections)


def generate_safe_boundaries_doc(scan: RepoScan, overrides: Overrides | None = None) -> str:
    """Generate content for ``.agent-memory/rules/safe-boundaries.md``.

    Lists paths that should never be edited, combining human ``never_edit``
    overrides with inferred boundaries (vendored code, generated files, etc.).

    Args:
        scan:      A populated :class:`~scanner.RepoScan`.
        overrides: Optional loaded :class:`~overrides.Overrides`.

    Returns:
        Markdown string suitable for writing to ``rules/safe-boundaries.md``.
    """
    sections: list[str] = []

    repo_name = scan.repo_root.name or "this-repo"
    sections.append(
        f"# Safe boundaries: {repo_name}\n\n"
        f"{_AUTO_GENERATED_NOTE}\n\n"
        "> Files and paths listed here must **never** be edited by automated agents "
        "without explicit human review."
    )

    # Human never_edit entries — authoritative, listed first
    if overrides and overrides.never_edit:
        human_lines = "\n".join(
            f"- `{p}` — marked never-edit by team" for p in overrides.never_edit
        )
        sections.append(render_markdown_section("Never edit (team rules)", human_lines))

    # Inferred boundaries from scan
    inferred = _infer_never_edit_paths(scan)
    if inferred:
        inferred_lines = "\n".join(f"- `{p}` — {reason}" for p, reason in inferred)
        sections.append(render_markdown_section("Inferred boundaries", inferred_lines))

    # Universal always-skip paths
    universal = "\n".join(f"- `{p}`" for p in _INFERRED_NEVER_EDIT)
    sections.append(render_markdown_section("Universal boundaries", universal))

    # Human notes flagging fragile areas
    if overrides and overrides.notes:
        notes_body = "\n".join(f"- {n}" for n in overrides.notes)
        sections.append(render_markdown_section("Fragile area notes", notes_body))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# Rule doc helpers
# ---------------------------------------------------------------------------


def _infer_project_conventions(scan: RepoScan) -> list[str]:
    """Infer notable project-level conventions from scan signals."""
    conventions: list[str] = []

    if scan.test_dirs:
        conventions.append(
            f"Tests live in `{'`, `'.join(scan.test_dirs)}/`. "
            "Always add tests for new behaviour."
        )

    if scan.docs_dirs:
        conventions.append(
            f"Documentation lives in `{'`, `'.join(scan.docs_dirs)}/`. "
            "Update docs when adding public APIs."
        )

    if "pyproject.toml" in scan.config_files:
        conventions.append(
            "Dependencies are managed via `pyproject.toml`. "
            "Use `uv` or `pip` to update them — never edit the lock file manually."
        )

    if "package.json" in scan.config_files:
        conventions.append(
            "Dependencies are managed via `package.json`. "
            "Use `npm install` or `yarn` — never edit `node_modules/` directly."
        )

    return conventions


def _infer_never_edit_paths(scan: RepoScan) -> list[tuple[str, str]]:
    """Return (path, reason) pairs for inferred never-edit boundaries."""
    inferred: list[tuple[str, str]] = []

    for dir_name in scan.top_level_dirs:
        lower = dir_name.lower()
        if lower in ("migrations", "migration"):
            inferred.append((f"{dir_name}/", "database migrations — append-only"))
        elif lower in ("vendor", "third_party", "thirdparty"):
            inferred.append((f"{dir_name}/", "vendored third-party code"))
        elif lower in ("generated", "gen", "auto_generated", "autogenerated"):
            inferred.append((f"{dir_name}/", "auto-generated code"))

    if "pyproject.toml" in scan.config_files:
        inferred.append(("uv.lock", "lock file — managed automatically"))
    if "package.json" in scan.config_files:
        inferred.append(("package-lock.json", "lock file — managed automatically"))
        inferred.append(("yarn.lock", "lock file — managed automatically"))

    return inferred


# ---------------------------------------------------------------------------
# CLAUDE.md
# ---------------------------------------------------------------------------


def generate_claude_memory_doc(scan: RepoScan, overrides: "Overrides | None" = None) -> str:
    """Generate content for ``.agent-memory/CLAUDE.md``.

    Produces a concise, Claude-facing memory file assembled from repo summary,
    architecture layout, coding conventions, and safe boundaries.  Designed
    for automatic pickup by Claude Code at session start — kept small and
    agent-readable (target: under 150 lines).

    Args:
        scan:      A populated :class:`~scanner.RepoScan`.
        overrides: Optional loaded :class:`~overrides.Overrides`.

    Returns:
        Markdown string suitable for writing to ``.agent-memory/CLAUDE.md``.
    """
    repo_name = scan.repo_root.name or "this-repo"
    sections: list[str] = []

    sections.append(
        f"# Repo memory: {repo_name}\n\n"
        "> Auto-generated by repo-memory — commit this file to share with your team.\n"
        "> Add domain corrections in `.agent-memory/overrides/`."
    )

    # Stack
    stack_parts: list[str] = []
    if scan.languages:
        stack_parts.append(f"**Languages:** {', '.join(sorted(scan.languages))}")
    if scan.framework_hints:
        stack_parts.append(f"**Frameworks:** {', '.join(sorted(scan.framework_hints))}")
    if scan.source_dirs:
        stack_parts.append(f"**Source dirs:** {', '.join(sorted(scan.source_dirs))}")
    if scan.test_dirs:
        stack_parts.append(f"**Test dirs:** {', '.join(sorted(scan.test_dirs))}")
    if stack_parts:
        sections.append(render_markdown_section("Stack", "\n".join(stack_parts)))

    # Top-level layout
    if scan.top_level_dirs:
        arch_lines = "\n".join(f"- `{d}/`" for d in sorted(scan.top_level_dirs)[:12])
        sections.append(render_markdown_section("Top-level layout", arch_lines))

    # Human notes — highest signal, always near the top
    if overrides and overrides.notes:
        notes_body = "\n".join(f"- {n}" for n in overrides.notes)
        sections.append(render_markdown_section("Team notes", notes_body))

    # Key conventions — compact: max 2 rules per language, 1 per framework
    conv_lines: list[str] = []
    for lang in sorted(scan.languages):
        for rule in _LANG_CONVENTIONS.get(lang, [])[:2]:
            conv_lines.append(f"- **{lang}**: {rule}")
    for fw in sorted(scan.framework_hints):
        for rule in _FRAMEWORK_CONVENTIONS.get(fw, [])[:1]:
            conv_lines.append(f"- **{fw}**: {rule}")
    if conv_lines:
        sections.append(render_markdown_section("Key conventions", "\n".join(conv_lines)))

    # Never-edit paths
    never_edit: list[str] = []
    if overrides and overrides.never_edit:
        never_edit.extend(overrides.never_edit)
    for dir_name in sorted(scan.top_level_dirs):
        if dir_name.lower() in ("migrations", "migration", "vendor", "third_party", "thirdparty"):
            candidate = f"{dir_name}/"
            if candidate not in never_edit:
                never_edit.append(candidate)
    if never_edit:
        ne_lines = "\n".join(f"- `{p}`" for p in never_edit[:8])
        sections.append(render_markdown_section("Never edit", ne_lines))

    # Task hints from overrides
    if overrides and overrides.task_hints:
        hint_lines = "\n".join(
            f"- **{th.pattern}**: {th.hint}" for th in overrides.task_hints[:5]
        )
        sections.append(render_markdown_section("Task hints", hint_lines))

    return "\n\n".join(sections)
