"""Memory artifact generator for the memory subsystem.

Turns structured scan/model data into human- and agent-readable markdown.
This module produces *content strings only* — it never writes to disk.
All disk I/O is handled by ``writer.py``.

Design constraints
------------------
- Deterministic: same inputs always produce the same string.
- Concise: optimised for agent context windows, not human prose.
- Graceful degradation: produces useful output even when signals are weak.
- No LLM calls: all generation is template/heuristic-driven.

Public API
----------
generate_repo_summary(scan)                        -> str  (content for repo.md)
generate_architecture_doc(scan)                    -> str  (content for architecture.md)
generate_feature_doc(feature)                      -> str  (content for features/<slug>.md)
generate_module_doc(module)                        -> str  (content for modules/<slug>.md)
generate_conventions_doc(scan, overrides)          -> str  (content for rules/conventions.md)
generate_safe_boundaries_doc(scan, overrides)      -> str  (content for rules/safe-boundaries.md)
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from .models import FeatureMemory, ModuleMemory
from .scanner import RepoScan
from .writer import render_markdown_section

if TYPE_CHECKING:
    from .overrides import Overrides

# Shared preamble for auto-generated files
_AUTO_GENERATED_NOTE = (
    "> Auto-generated by repo-memory. "
    "Add corrections in `.agent-memory/overrides/`."
)

# Max files to list in a section before truncating
_MAX_FILES_LISTED = 20

# ---------------------------------------------------------------------------
# repo.md
# ---------------------------------------------------------------------------

_REPO_PREAMBLE = (
    "> This file is auto-generated by repo-memory. "
    "Edit `.agent-memory/overrides/` to add human corrections."
)


def generate_repo_summary(scan: RepoScan) -> str:
    """Generate content for ``.agent-memory/repo.md``.

    Args:
        scan: A populated :class:`~scanner.RepoScan`.

    Returns:
        Markdown string suitable for writing directly to ``repo.md``.
    """
    sections: list[str] = []

    # H1 title
    repo_name = scan.repo_root.name or "this-repo"
    sections.append(f"# Repo: {repo_name}\n\n{_REPO_PREAMBLE}")

    # Purpose / stack
    sections.append(render_markdown_section(
        "Stack",
        _render_stack(scan),
    ))

    # Top-level structure
    sections.append(render_markdown_section(
        "Top-level structure",
        _render_top_level(scan),
    ))

    # Where things live
    sections.append(render_markdown_section(
        "Key locations",
        _render_key_locations(scan),
    ))

    # Starting points
    sections.append(render_markdown_section(
        "Suggested starting points",
        _render_starting_points(scan),
    ))

    # Ambiguity notes
    if scan.notes:
        sections.append(render_markdown_section(
            "Detection notes",
            _render_notes(scan.notes),
        ))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# architecture.md
# ---------------------------------------------------------------------------

_ARCH_PREAMBLE = (
    "> Auto-generated architectural overview. "
    "Confidence: {confidence:.0%}. "
    "Add corrections in `.agent-memory/overrides/`."
)


def generate_architecture_doc(scan: RepoScan) -> str:
    """Generate content for ``.agent-memory/architecture.md``.

    Args:
        scan: A populated :class:`~scanner.RepoScan`.

    Returns:
        Markdown string suitable for writing directly to ``architecture.md``.
    """
    sections: list[str] = []

    repo_name = scan.repo_root.name or "this-repo"
    preamble = _ARCH_PREAMBLE.format(confidence=scan.confidence)
    sections.append(f"# Architecture: {repo_name}\n\n{preamble}")

    # Major boundaries
    sections.append(render_markdown_section(
        "Major boundaries",
        _render_boundaries(scan),
    ))

    # Architectural layout
    sections.append(render_markdown_section(
        "Inferred layout",
        _render_layout(scan),
    ))

    # Coupling / ambiguity
    coupling = _render_coupling_notes(scan)
    if coupling:
        sections.append(render_markdown_section(
            "Coupling and ambiguity notes",
            coupling,
        ))

    # Inspect first
    sections.append(render_markdown_section(
        "Inspect first",
        _render_inspect_first(scan),
    ))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# Section renderers — repo.md
# ---------------------------------------------------------------------------


def _render_stack(scan: RepoScan) -> str:
    lines: list[str] = []

    if scan.languages:
        lines.append(f"- **Languages**: {', '.join(scan.languages)}")
    else:
        lines.append("- **Languages**: not detected")

    if scan.framework_hints:
        lines.append(f"- **Frameworks**: {', '.join(scan.framework_hints)}")

    if scan.file_counts:
        counts_str = ", ".join(
            f"{lang} ({n})" for lang, n in sorted(scan.file_counts.items(), key=lambda x: -x[1])
        )
        lines.append(f"- **File counts**: {counts_str}")

    if scan.config_files:
        lines.append(f"- **Config files**: {', '.join(sorted(scan.config_files))}")

    if not lines:
        lines.append("Stack not detected — see detection notes.")

    return "\n".join(lines)


def _render_top_level(scan: RepoScan) -> str:
    if not scan.top_level_dirs:
        return "No top-level directories detected."
    lines = [f"- `{d}/`" for d in sorted(scan.top_level_dirs)]
    return "\n".join(lines)


def _render_key_locations(scan: RepoScan) -> str:
    lines: list[str] = []

    if scan.source_dirs:
        lines.append(f"- **Source**: {', '.join(f'`{d}/`' for d in scan.source_dirs)}")
    else:
        lines.append("- **Source**: not clearly identified (may be at repo root)")

    if scan.test_dirs:
        lines.append(f"- **Tests**: {', '.join(f'`{d}/`' for d in scan.test_dirs)}")
    else:
        lines.append("- **Tests**: not detected")

    if scan.docs_dirs:
        lines.append(f"- **Docs**: {', '.join(f'`{d}/`' for d in scan.docs_dirs)}")
    else:
        lines.append("- **Docs**: not detected")

    if scan.readme_path:
        lines.append(f"- **README**: `{scan.readme_path}`")

    return "\n".join(lines)


def _render_starting_points(scan: RepoScan) -> str:
    points: list[str] = []

    if scan.readme_path:
        points.append(f"`{scan.readme_path}` — project overview")

    for f in scan.config_files:
        if f in ("pyproject.toml", "package.json", "go.mod", "Cargo.toml", "pom.xml"):
            points.append(f"`{f}` — dependencies and project metadata")
            break

    for d in scan.source_dirs[:2]:
        points.append(f"`{d}/` — main source code")

    for d in scan.test_dirs[:1]:
        points.append(f"`{d}/` — test suite")

    if not points:
        points.append("Explore the top-level directories listed above.")

    return "\n".join(f"- {p}" for p in points)


def _render_notes(notes: list[str]) -> str:
    return "\n".join(f"- {n}" for n in notes)


# ---------------------------------------------------------------------------
# Section renderers — architecture.md
# ---------------------------------------------------------------------------


def _render_boundaries(scan: RepoScan) -> str:
    """Describe major code boundaries based on directory structure."""
    boundaries: list[str] = []

    if scan.source_dirs:
        for d in scan.source_dirs:
            boundaries.append(f"- **`{d}/`** — production source code")

    if scan.test_dirs:
        for d in scan.test_dirs:
            boundaries.append(f"- **`{d}/`** — test suite (separate from production code)")

    if scan.docs_dirs:
        for d in scan.docs_dirs:
            boundaries.append(f"- **`{d}/`** — documentation")

    # Monorepo signal: multiple conventional dirs
    apps_dirs = [d for d in scan.top_level_dirs if d.lower() in ("apps", "packages", "services")]
    if apps_dirs:
        for d in apps_dirs:
            boundaries.append(f"- **`{d}/`** — multiple apps/packages (possible monorepo)")

    if not boundaries:
        boundaries.append(
            "- No clear boundaries detected. "
            "The codebase may be structured at the root level."
        )

    return "\n".join(boundaries)


def _render_layout(scan: RepoScan) -> str:
    """Infer and describe the high-level architectural layout."""
    lines: list[str] = []

    # Monorepo
    if any(d.lower() in ("apps", "packages", "services") for d in scan.top_level_dirs):
        lines.append("**Pattern**: Monorepo (multiple apps or packages in one repo)")
    elif scan.source_dirs:
        lines.append("**Pattern**: Single-application repo with dedicated source directory")
    else:
        lines.append("**Pattern**: Flat or non-standard layout")

    # Framework-specific layout hints
    if "Django" in scan.framework_hints:
        lines.append("**Django layout**: expect apps as subdirectories, `settings.py`, `urls.py`")
    if "FastAPI" in scan.framework_hints:
        lines.append("**FastAPI layout**: expect `main.py` / `app.py`, routers, models, schemas")
    if "Next.js" in scan.framework_hints:
        lines.append("**Next.js layout**: expect `pages/` or `app/`, `public/`, `components/`")
    if "React" in scan.framework_hints and "Next.js" not in scan.framework_hints:
        lines.append("**React layout**: expect `src/components/`, `src/hooks/`, `src/pages/`")

    if not lines:
        lines.append("Layout could not be confidently inferred from directory structure alone.")

    return "\n".join(lines)


def _render_coupling_notes(scan: RepoScan) -> str:
    """Surface coupling or ambiguity worth flagging."""
    notes: list[str] = []

    if len(scan.languages) > 3:
        notes.append(
            f"Multi-language repo ({', '.join(scan.languages)}). "
            "Check language boundaries before refactoring."
        )

    if not scan.test_dirs:
        notes.append(
            "No test directory detected. Test coverage is unknown — be cautious with changes."
        )

    if scan.confidence < 0.7:
        notes.append(
            f"Low-confidence scan ({scan.confidence:.0%}). "
            "Structural signals were weak; verify key locations manually."
        )

    # Pass through any scanner-generated notes
    for note in scan.notes:
        if note not in notes:
            notes.append(note)

    return "\n".join(f"- {n}" for n in notes) if notes else ""


def _render_inspect_first(scan: RepoScan) -> str:
    """Files/dirs worth looking at first when starting a task."""
    items: list[str] = []

    for d in scan.source_dirs[:3]:
        items.append(f"`{d}/` — main source code")

    for cfg in ("pyproject.toml", "package.json", "go.mod", "Cargo.toml"):
        if cfg in scan.config_files:
            items.append(f"`{cfg}` — project metadata and dependencies")
            break

    if scan.readme_path:
        items.append(f"`{scan.readme_path}` — project intent and setup")

    for d in scan.test_dirs[:1]:
        items.append(f"`{d}/` — to understand expected behaviour")

    if not items:
        items.append("No strong starting points detected — explore top-level directories.")

    return "\n".join(f"- {i}" for i in items)


# ---------------------------------------------------------------------------
# features/<slug>.md
# ---------------------------------------------------------------------------


def generate_feature_doc(feature: FeatureMemory) -> str:
    """Generate content for ``.agent-memory/features/<slug>.md``.

    Args:
        feature: A classified :class:`~models.FeatureMemory` instance.

    Returns:
        Markdown string ready to be written to disk by ``writer.py``.
    """
    sections: list[str] = []

    # Header
    confidence_note = _confidence_label(feature.confidence)
    sections.append(
        f"# Feature: {feature.name}\n\n"
        f"{_AUTO_GENERATED_NOTE}\n\n"
        f"**Confidence**: {feature.confidence:.0%} ({confidence_note})"
    )

    # Purpose — inferred from name and rationale
    sections.append(render_markdown_section(
        "Purpose",
        _feature_purpose(feature),
    ))

    # Main files
    sections.append(render_markdown_section(
        "Main files",
        _render_file_list(feature.files, "No source files detected."),
    ))

    # Likely entry points — first file alphabetically that isn't a model/schema
    entry_points = _infer_entry_points(feature.files)
    if entry_points:
        sections.append(render_markdown_section(
            "Likely entry points",
            _render_file_list(entry_points, ""),
        ))

    # Related tests
    sections.append(render_markdown_section(
        "Related tests",
        _render_file_list(feature.tests, "No related tests detected."),
    ))

    # Neighboring areas — other features that share files (populated by caller
    # in future; for now use dependencies field)
    if feature.dependencies:
        sections.append(render_markdown_section(
            "Neighboring areas",
            "\n".join(f"- {d}" for d in sorted(feature.dependencies)),
        ))

    # Warnings / ambiguity
    warnings = _feature_warnings(feature)
    if warnings:
        sections.append(render_markdown_section(
            "Warnings and notes",
            warnings,
        ))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# modules/<slug>.md
# ---------------------------------------------------------------------------


def generate_module_doc(module: ModuleMemory) -> str:
    """Generate content for ``.agent-memory/modules/<slug>.md``.

    Args:
        module: A classified :class:`~models.ModuleMemory` instance.

    Returns:
        Markdown string ready to be written to disk by ``writer.py``.
    """
    sections: list[str] = []

    # Header
    confidence_note = _confidence_label(module.confidence)
    sections.append(
        f"# Module: {module.name}\n\n"
        f"{_AUTO_GENERATED_NOTE}\n\n"
        f"**Confidence**: {module.confidence:.0%} ({confidence_note})"
    )

    # Purpose
    sections.append(render_markdown_section(
        "Purpose",
        _module_purpose(module),
    ))

    # Responsibilities — inferred from file names
    responsibilities = _infer_responsibilities(module.files)
    if responsibilities:
        sections.append(render_markdown_section(
            "Responsibilities",
            "\n".join(f"- {r}" for r in responsibilities),
        ))

    # Files
    sections.append(render_markdown_section(
        "Files",
        _render_file_list(module.files, "No source files detected."),
    ))

    # Dependencies
    if module.dependencies:
        sections.append(render_markdown_section(
            "Dependencies",
            "\n".join(f"- `{d}`" for d in sorted(module.dependencies)),
        ))

    # Dependents
    if module.dependents:
        sections.append(render_markdown_section(
            "Depended on by",
            "\n".join(f"- `{d}`" for d in sorted(module.dependents)),
        ))

    # Related tests
    sections.append(render_markdown_section(
        "Related tests",
        _render_file_list(module.tests, "No related tests detected."),
    ))

    # Risk / coupling notes
    risks = _module_risks(module)
    if risks:
        sections.append(render_markdown_section(
            "Risk and coupling notes",
            risks,
        ))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# Feature doc helpers
# ---------------------------------------------------------------------------


def _feature_purpose(feature: FeatureMemory) -> str:
    """Produce a one-line purpose statement for a feature doc."""
    name = feature.name
    source = _classification_source(feature.confidence)
    return (
        f"Implements the **{name}** product area "
        f"({len(feature.files)} file(s) detected; classified by {source})."
    )


def _feature_warnings(feature: FeatureMemory) -> str:
    """Return warning lines for a feature doc."""
    lines: list[str] = []
    if feature.confidence < 0.6:
        lines.append(
            f"Low confidence ({feature.confidence:.0%}): grouping is inferred from "
            "directory structure only — verify file membership manually."
        )
    if not feature.tests:
        lines.append("No test files linked to this feature. Coverage is unknown.")
    if len(feature.files) > _MAX_FILES_LISTED:
        lines.append(
            f"Large feature: {len(feature.files)} files total "
            f"(only first {_MAX_FILES_LISTED} shown above). "
            "Consider splitting into sub-features."
        )
    return "\n".join(f"- {line}" for line in lines)


def _infer_entry_points(files: list[str]) -> list[str]:
    """Return files likely to be entry points (routes, views, controllers, main)."""
    priority_stems = {
        "main", "app", "index", "server", "router", "routes",
        "views", "view", "controller", "controllers", "handler", "handlers",
        "api", "endpoint", "endpoints",
    }
    result = [
        f for f in files
        if Path(f).stem.lower() in priority_stems
    ]
    return sorted(result)[:5]


# ---------------------------------------------------------------------------
# Module doc helpers
# ---------------------------------------------------------------------------


def _module_purpose(module: ModuleMemory) -> str:
    """Produce a one-line purpose statement for a module doc."""
    name = module.name
    source = _classification_source(module.confidence)
    return (
        f"Provides the **{name}** package/module boundary "
        f"({len(module.files)} file(s); classified by {source})."
    )


def _infer_responsibilities(files: list[str]) -> list[str]:
    """Infer likely responsibilities from the file stems in this module."""
    # Map common file stems to responsibility descriptions
    stem_hints: dict[str, str] = {
        "models": "data models / ORM definitions",
        "model": "data model definitions",
        "views": "view / template rendering",
        "view": "view / template rendering",
        "routes": "URL routing / endpoint registration",
        "router": "request routing",
        "controller": "request handling / business dispatch",
        "controllers": "request handling / business dispatch",
        "service": "business logic / service layer",
        "services": "business logic / service layer",
        "middleware": "request/response middleware",
        "schema": "data schema / validation",
        "schemas": "data schema / validation",
        "serializer": "data serialisation",
        "serializers": "data serialisation",
        "utils": "shared utilities / helpers",
        "helpers": "shared helper functions",
        "config": "configuration management",
        "settings": "application settings",
        "migrations": "database schema migrations",
        "tasks": "background task definitions",
        "worker": "background worker / job processing",
        "client": "external API / service client",
        "main": "application entrypoint",
        "app": "application setup / factory",
        "index": "module public interface",
        "types": "type definitions / interfaces",
        "interfaces": "interface / contract definitions",
    }
    found: list[str] = []
    seen: set[str] = set()
    for f in sorted(files):
        stem = Path(f).stem.lower()
        if stem in stem_hints and stem_hints[stem] not in seen:
            found.append(stem_hints[stem])
            seen.add(stem_hints[stem])
    return found[:6]  # cap to avoid bloat


def _module_risks(module: ModuleMemory) -> str:
    """Return risk/coupling notes for a module doc."""
    lines: list[str] = []
    if module.confidence < 0.6:
        lines.append(
            f"Low confidence ({module.confidence:.0%}): boundary was inferred, "
            "not derived from explicit package structure."
        )
    if len(module.files) > _MAX_FILES_LISTED:
        lines.append(
            f"Large module: {len(module.files)} files. "
            "High file count may indicate coupling or missed sub-module boundaries."
        )
    if module.dependents:
        lines.append(
            f"This module is depended on by {len(module.dependents)} other module(s): "
            f"{', '.join(sorted(module.dependents)[:3])}. "
            "Changes here have broad impact."
        )
    return "\n".join(f"- {line}" for line in lines)


# ---------------------------------------------------------------------------
# Shared rendering helpers
# ---------------------------------------------------------------------------


def _render_file_list(files: list[str], empty_msg: str) -> str:
    """Render a sorted list of files as markdown bullets, truncating if large."""
    if not files:
        return empty_msg
    shown = sorted(files)[:_MAX_FILES_LISTED]
    lines = [f"- `{f}`" for f in shown]
    if len(files) > _MAX_FILES_LISTED:
        lines.append(f"- _…and {len(files) - _MAX_FILES_LISTED} more_")
    return "\n".join(lines)


def _confidence_label(confidence: float) -> str:
    if confidence >= 0.85:
        return "high — derived from explicit package structure"
    if confidence >= 0.65:
        return "medium — inferred from directory naming"
    return "low — heuristic grouping, verify manually"


def _classification_source(confidence: float) -> str:
    if confidence >= 0.85:
        return "explicit package boundary"
    if confidence >= 0.65:
        return "directory name heuristic"
    return "weak heuristic (low confidence)"


# ---------------------------------------------------------------------------
# rules/conventions.md
# ---------------------------------------------------------------------------

# Inferred language-level conventions
_LANG_CONVENTIONS: dict[str, list[str]] = {
    "python": [
        "Follow PEP 8 style (4-space indent, max 79–100 chars per line).",
        "Use type annotations on all public functions.",
        "Prefer `pathlib.Path` over `os.path` for file operations.",
    ],
    "typescript": [
        "Use strict TypeScript (`strict: true` in tsconfig).",
        "Prefer `interface` over `type` for object shapes.",
        "Avoid `any`; use `unknown` and narrow explicitly.",
    ],
    "javascript": [
        "Prefer `const` over `let`; avoid `var`.",
        "Use ES modules (`import`/`export`) over CommonJS.",
    ],
    "go": [
        "Return errors explicitly; never ignore them.",
        "Keep package names short and lowercase.",
        "Use `gofmt` formatting.",
    ],
    "rust": [
        "Handle `Result` and `Option` explicitly — no `unwrap()` in production paths.",
        "Prefer owned types unless sharing is necessary.",
    ],
    "java": [
        "Follow Google Java Style Guide.",
        "Prefer composition over inheritance.",
    ],
}

# Inferred framework-level conventions
_FRAMEWORK_CONVENTIONS: dict[str, list[str]] = {
    "Django": [
        "Keep business logic in services, not views.",
        "Manage schema changes via `makemigrations` — never edit migrations manually.",
    ],
    "FastAPI": [
        "Use Pydantic schemas for all request/response bodies.",
        "Register routers in `main.py` or `app.py`.",
    ],
    "React": [
        "Keep components small and single-purpose.",
        "Lift shared state up to the nearest common ancestor.",
    ],
    "Next.js": [
        "Prefer server components over client components for data fetching.",
        "Use `app/` directory structure for Next.js 13+.",
    ],
}

# Paths that are almost universally never-edit
_INFERRED_NEVER_EDIT: list[str] = [
    "node_modules/",
    ".git/",
    "__pycache__/",
    "*.min.js",
    "*.min.css",
    "dist/",
    "build/",
    ".venv/",
    "venv/",
]


def generate_conventions_doc(scan: RepoScan, overrides: Overrides | None = None) -> str:
    """Generate content for ``.agent-memory/rules/conventions.md``.

    Combines inferred language/framework conventions with human notes from
    override files. Human notes are always included verbatim at the top.

    Args:
        scan:      A populated :class:`~scanner.RepoScan`.
        overrides: Optional loaded :class:`~overrides.Overrides`; ``None``
                   produces inference-only output.

    Returns:
        Markdown string suitable for writing to ``rules/conventions.md``.
    """
    sections: list[str] = []

    repo_name = scan.repo_root.name or "this-repo"
    sections.append(
        f"# Conventions: {repo_name}\n\n"
        f"{_AUTO_GENERATED_NOTE}"
    )

    # Human notes first — they are authoritative
    if overrides and overrides.notes:
        notes_body = "\n".join(f"- {n}" for n in overrides.notes)
        sections.append(render_markdown_section("Team notes", notes_body))

    # Language conventions
    lang_lines: list[str] = []
    for lang in sorted(scan.languages):
        for rule in _LANG_CONVENTIONS.get(lang, []):
            lang_lines.append(f"- **{lang}**: {rule}")
    if lang_lines:
        sections.append(render_markdown_section("Language conventions", "\n".join(lang_lines)))

    # Framework conventions
    fw_lines: list[str] = []
    for fw in sorted(scan.framework_hints):
        for rule in _FRAMEWORK_CONVENTIONS.get(fw, []):
            fw_lines.append(f"- **{fw}**: {rule}")
    if fw_lines:
        sections.append(render_markdown_section("Framework conventions", "\n".join(fw_lines)))

    # Project-level conventions inferred from scan signals
    inferred = _infer_project_conventions(scan)
    if inferred:
        sections.append(render_markdown_section(
            "Inferred project patterns",
            "\n".join(f"- {c}" for c in inferred),
        ))

    if len(sections) == 1:
        sections.append(
            "> No conventions detected. "
            "Add notes in `.agent-memory/overrides/global.yaml` to guide Claude Code."
        )

    return "\n\n".join(sections)


def generate_safe_boundaries_doc(scan: RepoScan, overrides: Overrides | None = None) -> str:
    """Generate content for ``.agent-memory/rules/safe-boundaries.md``.

    Lists paths that should never be edited, combining human ``never_edit``
    overrides with inferred boundaries (vendored code, generated files, etc.).

    Args:
        scan:      A populated :class:`~scanner.RepoScan`.
        overrides: Optional loaded :class:`~overrides.Overrides`.

    Returns:
        Markdown string suitable for writing to ``rules/safe-boundaries.md``.
    """
    sections: list[str] = []

    repo_name = scan.repo_root.name or "this-repo"
    sections.append(
        f"# Safe boundaries: {repo_name}\n\n"
        f"{_AUTO_GENERATED_NOTE}\n\n"
        "> Files and paths listed here must **never** be edited by automated agents "
        "without explicit human review."
    )

    # Human never_edit entries — authoritative, listed first
    if overrides and overrides.never_edit:
        human_lines = "\n".join(
            f"- `{p}` — marked never-edit by team" for p in overrides.never_edit
        )
        sections.append(render_markdown_section("Never edit (team rules)", human_lines))

    # Inferred boundaries from scan
    inferred = _infer_never_edit_paths(scan)
    if inferred:
        inferred_lines = "\n".join(f"- `{p}` — {reason}" for p, reason in inferred)
        sections.append(render_markdown_section("Inferred boundaries", inferred_lines))

    # Universal always-skip paths
    universal = "\n".join(f"- `{p}`" for p in _INFERRED_NEVER_EDIT)
    sections.append(render_markdown_section("Universal boundaries", universal))

    # Human notes flagging fragile areas
    if overrides and overrides.notes:
        notes_body = "\n".join(f"- {n}" for n in overrides.notes)
        sections.append(render_markdown_section("Fragile area notes", notes_body))

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# Rule doc helpers
# ---------------------------------------------------------------------------


def _infer_project_conventions(scan: RepoScan) -> list[str]:
    """Infer notable project-level conventions from scan signals."""
    conventions: list[str] = []

    if scan.test_dirs:
        conventions.append(
            f"Tests live in `{'`, `'.join(scan.test_dirs)}/`. "
            "Always add tests for new behaviour."
        )

    if scan.docs_dirs:
        conventions.append(
            f"Documentation lives in `{'`, `'.join(scan.docs_dirs)}/`. "
            "Update docs when adding public APIs."
        )

    if "pyproject.toml" in scan.config_files:
        conventions.append(
            "Dependencies are managed via `pyproject.toml`. "
            "Use `uv` or `pip` to update them — never edit the lock file manually."
        )

    if "package.json" in scan.config_files:
        conventions.append(
            "Dependencies are managed via `package.json`. "
            "Use `npm install` or `yarn` — never edit `node_modules/` directly."
        )

    return conventions


def _infer_never_edit_paths(scan: RepoScan) -> list[tuple[str, str]]:
    """Return (path, reason) pairs for inferred never-edit boundaries."""
    inferred: list[tuple[str, str]] = []

    for dir_name in scan.top_level_dirs:
        lower = dir_name.lower()
        if lower in ("migrations", "migration"):
            inferred.append((f"{dir_name}/", "database migrations — append-only"))
        elif lower in ("vendor", "third_party", "thirdparty"):
            inferred.append((f"{dir_name}/", "vendored third-party code"))
        elif lower in ("generated", "gen", "auto_generated", "autogenerated"):
            inferred.append((f"{dir_name}/", "auto-generated code"))

    if "pyproject.toml" in scan.config_files:
        inferred.append(("uv.lock", "lock file — managed automatically"))
    if "package.json" in scan.config_files:
        inferred.append(("package-lock.json", "lock file — managed automatically"))
        inferred.append(("yarn.lock", "lock file — managed automatically"))

    return inferred
